name: "Hello world"

on: 
    push:
        branches:
            - main
            - prod

jobs: 
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello world"