name: "Hello world"

on: 
    push:
        branches:
            - main
            - prod

jobs:
    hello_world:
        runs-on: ubuntu -latest
        steps:
            - name: "Print hello world"
            run: echo "Hello World"